project_name: starlink_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - main: ./cmd/starlink_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - idoqo/{{.ProjectName}}:v{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - idoqo/{{.ProjectName}}:v{{ .Version }}-arm7
    use: buildx
    dockerfile: Dockerfile
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"

  - image_templates:
      - idoqo/{{.ProjectName}}:v{{ .Version }}-arm64
    use: buildx
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  # dockerhub
  - name_template: idoqo/{{.ProjectName}}:v{{ .Version }}
    image_templates:
      - idoqo/{{.ProjectName}}:v{{ .Version }}-amd64
      - idoqo/{{.ProjectName}}:v{{ .Version }}-arm64
      - idoqo/{{.ProjectName}}:v{{ .Version }}-arm7
  - name_template: idoqo/{{.ProjectName}}:latest
    image_templates:
      - idoqo/{{.ProjectName}}:v{{ .Version }}-amd64
      - idoqo/{{.ProjectName}}:v{{ .Version }}-arm64
      - idoqo/{{.ProjectName}}:v{{ .Version }}-arm7
